// Code generated by mockery v2.37.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DBKeeperer is an autogenerated mock type for the DBKeeperer type
type DBKeeperer struct {
	mock.Mock
}

// Ping provides a mock function with given fields: ctx
func (_m *DBKeeperer) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDBKeeperer creates a new instance of DBKeeperer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDBKeeperer(t interface {
	mock.TestingT
	Cleanup(func())
}) *DBKeeperer {
	mock := &DBKeeperer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
