// Code generated by mockery v2.37.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DBPinger is an autogenerated mock type for the DBPinger type
type DBPinger struct {
	mock.Mock
}

// PingContext provides a mock function with given fields: ctx
func (_m *DBPinger) PingContext(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDBPinger creates a new instance of DBPinger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDBPinger(t interface {
	mock.TestingT
	Cleanup(func())
}) *DBPinger {
	mock := &DBPinger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
