// Code generated by mockery v2.37.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Keeperer is an autogenerated mock type for the Keeperer type
type Keeperer struct {
	mock.Mock
}

// GetURL provides a mock function with given fields: id
func (_m *Keeperer) GetURL(id string) (string, error) {
	ret := _m.Called(id)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostURL provides a mock function with given fields: url
func (_m *Keeperer) PostURL(url string) (string, error) {
	ret := _m.Called(url)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(url)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewKeeperer creates a new instance of Keeperer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeeperer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Keeperer {
	mock := &Keeperer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
